//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// ToolTest.rc에서 사용되고 있습니다.
//
#define IDCANCEL                        2
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_DOCKING_VIEW                101
#define IDS_ObjectInfo_View             102
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_ToolTestTYPE                130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_CreateMap                   311
#define IDD_MapProp                     315
#define IDR_MENU1                       319
#define IDR_MapMenu                     319
#define IDD_DIALOG1                     320
#define IDD_MngDialog                   320
#define IDD_Create                      328
#define IDD_Create2                     329
#define IDD_FbxLoader                   331
#define IDD_ShowMapInfo                 332
#define IDD_InfoBtnDlg                  332
#define IDD_ObjectInfo                  338
#define IDD_MapControl                  341
#define IDD_LoadSubTxt                  342
#define IDC_MapSize                     1000
#define IDC_MapInfo                     1001
#define IDC_MapTexture                  1002
#define IDC_MapWidth                    1003
#define IDC_MapHeight                   1004
#define IDC_Texture                     1005
#define IDC_CellDistance                1006
#define IDC_MapCellDis                  1007
#define IDC_SPIN1                       1011
#define IDC_SpinMapW                    1011
#define IDC_SPIN2                       1012
#define IDC_SPINMapH                    1012
#define ID_CreateMapSize                1013
#define IDC_TextureName                 1014
#define ID_CreateTexture                1015
#define IDC_LoadFile                    1016
#define IDC_CellCombo                   1019
#define IDC_ButtonGroup                 1026
#define IDC_BUTTON2                     1027
#define IDC_Manage                      1027
#define IDC_Picking                     1027
#define IDC_YAxis                       1027
#define IDC_CancleCtl                   1027
#define IDC_Cancle                      1027
#define IDC_ObjectPickingBtn            1027
#define IDC_BUTTON3                     1028
#define IDC_Modify                      1028
#define IDC_XAxis                       1028
#define IDC_LoadSubTx                   1028
#define IDC_BUTTON4                     1029
#define IDC_Paint                       1029
#define IDC_BUTTON1                     1029
#define IDC_ADD                         1029
#define IDC_MapUp                       1029
#define IDC_SelectBtn                   1029
#define IDC_ScaleBtn                    1029
#define IDC_BUTTON5                     1030
#define IDC_ChildDialog                 1030
#define IDC_BUTTON6                     1031
#define IDC_LoadFbx                     1031
#define IDC_MapFlat                     1031
#define IDC_RotBtn                      1031
#define IDC_BUTTON7                     1032
#define IDC_SaveBtn                     1032
#define IDC_BUTTON8                     1033
#define ID_Create                       1033
#define IDC_LoadBtn                     1033
#define IDC_BUTTON9                     1034
#define IDC_CreateInfo                  1034
#define IDC_ShowInfo                    1034
#define IDC_BUTTON10                    1035
#define IDC_BUTTON11                    1036
#define IDC_MngMenu                     1052
#define IDC_COMBO1                      1053
#define IDC_COMBO2                      1054
#define IDC_COMBO3                      1055
#define IDC_MapCell                     1055
#define IDC_TextureFileName             1057
#define IDC_WireFrame                   1058
#define IDC_ShowMapInfo                 1059
#define IDC_TextureLoad                 1061
#define IDC_TexImg                      1062
#define IDC_UpdateTexture               1063
#define IDC_RenderOpt                   1066
#define IDC_FbxButton                   1067
#define IDC_FbxList                     1068
#define IDC_InfoBtn                     1069
#define IDC_ShowInfoBtn                 1070
#define IDC_Name                        1071
#define IDC_ObjectName                  1072
#define IDC_PickState                   1074
#define IDC_RangeText                   1077
#define IDC_PosBtn                      1078
#define IDC_ZAxis                       1079
#define IDC_ButtonGrp                   1081
#define IDC_XPos                        1082
#define IDC_MapDown                     1083
#define IDC_YPos                        1083
#define IDC_ControlStatus               1084
#define IDC_ZPos                        1084
#define IDC_ToolStrength                1085
#define IDC_XRot                        1085
#define IDC_Range                       1086
#define IDC_YRot                        1086
#define IDC_ZRot                        1087
#define IDC_StrengthText                1088
#define IDC_XScale                      1088
#define IDC_YScale                      1089
#define IDC_ZScale                      1090
#define IDC_ObjectPicking               1096
#define IDC_SeletcObjName               1097
#define IDC_SubTxList                   1098
#define IDC_SeletedSubTx                1099
#define ID_32771                        32771
#define ID_32772                        32772
#define ID_32773                        32773
#define ID_CreateMap                    32774
#define ID_SaveMao                      32775
#define ID_SaveMap                      32776
#define ID_LoadMap                      32777
#define ID_Test                         32780
#define ID_32781                        32781
#define ID_DOCKING_VIEW                 32782
#define ID_32783                        32783

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        342
#define _APS_NEXT_COMMAND_VALUE         32784
#define _APS_NEXT_CONTROL_VALUE         1100
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
